config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # MEMO: 色々試したい場合はこのページを使う
  # get "/sample" => "sample#index", as: :sample

  get "/" => redirect("/users/sign_in")

  namespace :mypage do
    get "/" => "mypage#index"
    resources :groups, only: [:new, :create, :show, :edit, :update, :destroy] do
      member do
        get 'confirm_destroy' # 削除前確認画面
      end
      resources :group_members, only: [:index] do
        member do
          get 'add'
        end
      end
      resources :albums, only: [:new, :create, :show, :edit, :update, :destroy] do
        member do
          get 'confirm_destroy'  # 削除前確認画面
        end
        resources :media_items, only: [:new, :show]
      end
    end
    resource :users, only: [:edit, :update] do
    end
  end

  # 静的ページ
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'
  get '/about', to: 'pages#about'

  # API
  namespace :api do
    namespace :v1 do
      resources :albums do
        resources :media_items, only: [:create, :destroy] do
          resources :media_item_comments, only: [:create, :destroy]
        end
      end
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_members, dependent: :destroy
  has_many :albums, dependent: :destroy

  validates :name, presence: true
end

app/controllers/mypage/albums_controller.rb
class Mypage::AlbumsController < Mypage::MypageApplicationController
  def new
    @album = current_user.groups.find(params[:group_id]).albums.new
  end

  def create
    album = current_user.groups.find(params[:group_id]).albums.new(album_params)
    if album.save
      redirect_to mypage_group_album_path(group_id: album.group.id, id: album.id), notice: 'アルバムを作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @album = current_user.albums.
      includes(media_items: { thumbnail_attachment: :blob }).
      find(params[:id])
    @media_items = @album.media_items.includes(thumbnail_attachment: :blob, media_attachment: :blob).order(id: :desc)
  end

  def confirm_destroy
    @album = current_user.albums.find(params[:id])
    unless current_user.this_group_master?(@album.group.id)
      redirect_to mypage_group_album_path(group_id: @album.group.id, id: @album.id),
alert: 'オーナーのみが可能な操作です'
    end
  end

  def edit
    @album = current_user.albums.find(params[:id])
  end

  def update
    @album = current_user.albums.find(params[:id])
    if @album.update(album_params)
      redirect_to mypage_group_album_path(group_id: @album.group.id, id: @album.id), notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = current_user.albums.find(params[:id])
    unless current_user.this_group_master?(@album.group.id)
      redirect_to mypage_group_album_path(group_id: @album.group.id, id: @album.id),
alert: 'オーナーのみが可能な操作です'
    end
    @album.destroy!
    redirect_to mypage_group_path(id: @album.group.id), notice: 'アルバムを削除しました'
  end

  private

  def album_params
    params.require(:album).permit(:name, :catchphrase)
  end
end

app/controllers/mypage/group_members_controller.rb
class Mypage::GroupMembersController < Mypage::MypageApplicationController
  include Encryption

  def index
    @group = current_user.groups.find(params[:group_id])
  end

  def add
    encrypted_gid = params[:id]
    decrypted_gid = Encryption.decrypt(encrypted_gid)

    return redirect_to mypage_group_path(id: group.id), notice: 'URLに誤りがあります' if params[:group_id] != decrypted_gid

    # 参加済みの場合はリダイレクト
    group = Group.find(params[:group_id])
    exists = group.group_members.exists?(user_id: current_user.id)
    return redirect_to mypage_group_path(id: group.id), notice: 'すでに参加しています' if exists

    # グループメンバーに参加
    group.group_members.create(user: current_user, is_master: false)
    redirect_to mypage_group_path(id: @group.id), notice: '参加しました'
  end
end

app/controllers/mypage/groups_controller.rb
class Mypage::GroupsController < Mypage::MypageApplicationController
  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    if group.save && group.group_members.create(user: current_user, is_master: true)
      redirect_to mypage_path, notice: 'グループを作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @group = current_user.groups.includes(albums: :media_items).find(params[:id])
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to mypage_group_path(@group), notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def confirm_destroy
    @group = current_user.groups.find(params[:id])
    redirect_to mypage_group_path(@group), alert: 'オーナーのみが可能な操作です' unless current_user.this_group_master?(@group.id)
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    redirect_to mypage_group_path(@group), alert: 'オーナーのみが可能な操作です' unless current_user.this_group_master?(@group.id)
    @group.destroy!
    redirect_to mypage_path, notice: 'グループを削除しました'
  end

  private

  def group_params
    params.require(:group).permit(:name, :catchphrase)
  end
end

app/controllers/mypage/media_items_controller.rb
class Mypage::MediaItemsController < Mypage::MypageApplicationController
  def new
    @album = current_user.albums.find(params[:album_id])
  end

  def show
    @media_item = current_user.media_items.includes(comments: :user).find(params[:id])
  end
end

app/controllers/mypage/mypage_application_controller.rb
class Mypage::MypageApplicationController < ApplicationController
  before_action :debug_login
  before_action :check_login

  # デバッグのためのログイン
  # MEMO: 開発中にログインが面倒な時はコメントアウトを外してください
  def debug_login
    # return unless Rails.env.development?
    # user = User.first
    # sign_in(user)
  end

  def check_login
    # ログインしていない場合はログインページにリダイレクト
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/mypage/mypage_controller.rb
class Mypage::MypageController < Mypage::MypageApplicationController
  def index
  end
end

app/controllers/mypage/users_controller.rb
class Mypage::UsersController < Mypage::MypageApplicationController
  def edit
    # ダミーのメアドが設定されている場合は編集画面で表示しない
    current_user.email = '' if current_user.dummy_email?
  end

  def update
    if current_user.update(user_params)
      redirect_to mypage_path, notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/views/mypage/groups/_group_form.html.erb
<%= form_with model: @group, url: url, local: true do |form| %>
    <%= render 'shared/input_form_text', form: form, field: :name, field_label: "グループ名", field_required: true, placeholder: 'マイファミリー🌸' %>
    <%= render 'shared/input_form_text', form: form, field: :catchphrase, field_label: "説明", field_required: false, placeholder: '家族の思いでを共有しましょう' %>
    <%= render 'shared/input_button', button_text: button_text, form: form %>
<% end %>

app/views/mypage/groups/confirm_destroy.html.erb
<% content_for :title, '削除' %>
<div class='container mx-auto py-8 w-full max-w-xl flex-grow outline-nones'>
    <% breadcrumb :confirm_destroy_mypage_group, @group %>
    <%= render 'shared/page_title', title: '削除' %>

    <div class='my-8 text-error-red font-bold'>
        <p>※グループに投稿された写真・動画は全て削除されて復元することはできません</p>
        <p>※この操作は取り消すことができません</p>
    </div>

    <p>「<%= @group.name %>」と入力してください</p>
    <div class="flex items-center bg-primary-default rounded border-0 cursor-text relative w-full">
        <%= text_field_tag 'js-confirm-name', nil, required: true, placeholder: @group.name, class: 'block w-full text-base leading-snug text-gray-700 bg-transparent p-4', id: 'js-confirm-name' %>
        <fieldset class="absolute inset-0 m-0 p-0 border border-transparent pointer-events-none"></fieldset>
    </div>

    <div class='my-8'></div>

    <%= form_with model: @group, url: mypage_group_path(@group), method: :delete do |form| %>
        <%= render 'shared/input_button', button_text: '削除する', disabled: true, button_id: 'js-delete-button', form: form %>
    <% end %>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const inputField = document.getElementById('js-confirm-name');
    const deleteButton = document.getElementById('js-delete-button');
    const groupName = "<%= @group.name %>";

    inputField.addEventListener('input', function() {
        if(inputField.value === groupName) {
            deleteButton.disabled = false;
            deleteButton.classList.remove('opacity-70');
        } else {
            deleteButton.disabled = true;
            deleteButton.classList.add('opacity-70');
        }
    });
});

</script>

app/views/mypage/groups/edit.html.erb
<% content_for :title, "#{@group.name} の編集" %>
<div class='container mx-auto py-8 w-full max-w-xl flex-grow outline-nones'>
    <% breadcrumb :edit_mypage_group, @group %>
    <%= render 'shared/page_title', title: "編集" %>
    <div class="container mx-auto py-8">
        <%= render 'mypage/groups/group_form', url: mypage_group_path(@group), button_text: "更新する" %>
    </div>
</div>

app/views/mypage/groups/new.html.erb
<% content_for :title, "グループ作成" %>
<div class='container mx-auto py-8 w-full max-w-xl flex-grow outline-nones'>
    <% breadcrumb :new_mypage_group %>
    <%= render 'shared/page_title', title: 'グループ作成' %>
    <div class="container mx-auto py-8">
        <%= render 'mypage/groups/group_form', url: mypage_groups_path, button_text: "作成する" %>
    </div>
</div>

app/views/mypage/groups/show.html.erb
<% content_for :title, @group.name %>
<div class='container mx-auto py-8 w-full max-w-xl flex-grow outline-nones'>
    <% breadcrumb :mypage_group, @group %>
    <%= render 'shared/page_title', title: @group.name %>

    <div class='my-8'>
        <%= @group.catchphrase %>
    </div>

    <section class='mb-8'>
        <%= render 'shared/list_title', title: '設定' %>
        <%= render 'shared/list_item', title: '' %>
        <%= link_to edit_mypage_group_path(@group) do %>
            <%= render 'shared/list_item', title: 'グループの編集' %>
        <% end %>
        <% if current_user.this_group_master?(@group.id) %>
            <%= link_to mypage_group_group_members_path(@group) do %>
                <%= render 'shared/list_item', title: 'メンバーの管理' %>
            <% end %>
            <%= link_to confirm_destroy_mypage_group_path(@group) do %>
                <%= render 'shared/list_item', title: 'グループの削除' %>
            <% end %>
        <% end %>
    </section>

    <section class='mb-8'>
        <%= render 'shared/list_title', title: 'アルバム' %>
        <%= render 'shared/list_item', title: '' %>
        <% @group.albums.each do |album| %>
            <%= link_to mypage_group_album_path(group_id: @group.id, id: album.id) do %>
                <%= render 'shared/list_item', title: album.name %>
            <% end %>
        <% end %>
        <%= link_to new_mypage_group_album_path(group_id: @group.id) do %>
            <%= render 'shared/add_action_label', text: 'アルバムを作成する' %>
        <% end %>
    </section>

</div>