config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # MEMO: 色々試したい場合はこのページを使う
  # get "/sample" => "sample#index", as: :sample

  get "/" => redirect("/users/sign_in")

  namespace :mypage do
    get "/" => "mypage#index"
    resources :groups, only: [:new, :create, :show, :edit, :update, :destroy] do
      member do
        get 'confirm_destroy' # 削除前確認画面
      end
      resources :group_members, only: [:index] do
        member do
          get 'add'
        end
      end
      resources :albums, only: [:new, :create, :show, :edit, :update, :destroy] do
        member do
          get 'confirm_destroy'  # 削除前確認画面
        end
        resources :media_items, only: [:new, :show]
      end
    end
    resource :users, only: [:edit, :update] do
    end
  end

  # 静的ページ
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'
  get '/about', to: 'pages#about'

  # API
  namespace :api do
    namespace :v1 do
      resources :albums do
        resources :media_items, only: [:create, :destroy] do
          resources :media_item_comments, only: [:create, :destroy]
        end
      end
    end
  end
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :user_id, presence: true
  validates :group_id, presence: true
end

app/controllers/mypage/albums_controller.rb
class Mypage::AlbumsController < Mypage::MypageApplicationController
  def new
    @album = current_user.groups.find(params[:group_id]).albums.new
  end

  def create
    album = current_user.groups.find(params[:group_id]).albums.new(album_params)
    if album.save
      redirect_to mypage_group_album_path(group_id: album.group.id, id: album.id), notice: 'アルバムを作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @album = current_user.albums.
      includes(media_items: { thumbnail_attachment: :blob }).
      find(params[:id])
    @media_items = @album.media_items.includes(thumbnail_attachment: :blob, media_attachment: :blob).order(id: :desc)
  end

  def confirm_destroy
    @album = current_user.albums.find(params[:id])
    unless current_user.this_group_master?(@album.group.id)
      redirect_to mypage_group_album_path(group_id: @album.group.id, id: @album.id),
alert: 'オーナーのみが可能な操作です'
    end
  end

  def edit
    @album = current_user.albums.find(params[:id])
  end

  def update
    @album = current_user.albums.find(params[:id])
    if @album.update(album_params)
      redirect_to mypage_group_album_path(group_id: @album.group.id, id: @album.id), notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = current_user.albums.find(params[:id])
    unless current_user.this_group_master?(@album.group.id)
      redirect_to mypage_group_album_path(group_id: @album.group.id, id: @album.id),
alert: 'オーナーのみが可能な操作です'
    end
    @album.destroy!
    redirect_to mypage_group_path(id: @album.group.id), notice: 'アルバムを削除しました'
  end

  private

  def album_params
    params.require(:album).permit(:name, :catchphrase)
  end
end

app/controllers/mypage/group_members_controller.rb
class Mypage::GroupMembersController < Mypage::MypageApplicationController
  include Encryption

  def index
    @group = current_user.groups.find(params[:group_id])
  end

  def add
    encrypted_gid = params[:id]
    decrypted_gid = Encryption.decrypt(encrypted_gid)

    return redirect_to mypage_group_path(id: group.id), notice: 'URLに誤りがあります' if params[:group_id] != decrypted_gid

    # 参加済みの場合はリダイレクト
    group = Group.find(params[:group_id])
    exists = group.group_members.exists?(user_id: current_user.id)
    return redirect_to mypage_group_path(id: group.id), notice: 'すでに参加しています' if exists

    # グループメンバーに参加
    group.group_members.create(user: current_user, is_master: false)
    redirect_to mypage_group_path(id: @group.id), notice: '参加しました'
  end
end

app/controllers/mypage/groups_controller.rb
class Mypage::GroupsController < Mypage::MypageApplicationController
  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    if group.save && group.group_members.create(user: current_user, is_master: true)
      redirect_to mypage_path, notice: 'グループを作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @group = current_user.groups.includes(albums: :media_items).find(params[:id])
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to mypage_group_path(@group), notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def confirm_destroy
    @group = current_user.groups.find(params[:id])
    redirect_to mypage_group_path(@group), alert: 'オーナーのみが可能な操作です' unless current_user.this_group_master?(@group.id)
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    redirect_to mypage_group_path(@group), alert: 'オーナーのみが可能な操作です' unless current_user.this_group_master?(@group.id)
    @group.destroy!
    redirect_to mypage_path, notice: 'グループを削除しました'
  end

  private

  def group_params
    params.require(:group).permit(:name, :catchphrase)
  end
end

app/controllers/mypage/media_items_controller.rb
class Mypage::MediaItemsController < Mypage::MypageApplicationController
  def new
    @album = current_user.albums.find(params[:album_id])
  end

  def show
    @media_item = current_user.media_items.includes(comments: :user).find(params[:id])
  end
end

app/controllers/mypage/mypage_application_controller.rb
class Mypage::MypageApplicationController < ApplicationController
  before_action :debug_login
  before_action :check_login

  # デバッグのためのログイン
  # MEMO: 開発中にログインが面倒な時はコメントアウトを外してください
  def debug_login
    # return unless Rails.env.development?
    # user = User.first
    # sign_in(user)
  end

  def check_login
    # ログインしていない場合はログインページにリダイレクト
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/mypage/mypage_controller.rb
class Mypage::MypageController < Mypage::MypageApplicationController
  def index
  end
end

app/controllers/mypage/users_controller.rb
class Mypage::UsersController < Mypage::MypageApplicationController
  def edit
    # ダミーのメアドが設定されている場合は編集画面で表示しない
    current_user.email = '' if current_user.dummy_email?
  end

  def update
    if current_user.update(user_params)
      redirect_to mypage_path, notice: '更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/views/mypage/group_members/index.html.erb
<% content_for :title, "メンバー管理" %>
<div class='container mx-auto py-8 w-full max-w-xl flex-grow outline-none'>
    <% breadcrumb :mypage_group_group_members, @group %>
    <%= render 'shared/page_title', title: 'メンバー管理' %>
    <div class="container mx-auto py-8">
        <%= render 'shared/list_title', title: '参加中のメンバー' %>
        <%= render 'shared/list_item', title: '' %>
        <% @group.group_members.each do |member| %>
            <section class='mb-4'>
                <% if member.is_master %>
                    <div class="ml-2 inline-flex align-text-bottom">
                        <span class="bg-gray-300 text-gray-800 text-xs font-bold leading-snug py-0.5 px-1 inline-flex items-center">
                            <span class="max-w-xs overflow-hidden truncate">
                                オーナー
                            </span>
                        </span>
                    </div>
                <% end %>
                <%= member.user.name %>
            </section>
            <%= render 'shared/list_item', title: '' %>
        <% end %>
        <div id='js-ionvite' class='w-fit cursor-pointer'>
            <%= render 'shared/add_action_label', text: 'メンバーを招待する' %>
        </div>
    </div>
</div>

<!-- モーダル -->
<div id="inviteModal" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
    <div class="bg-white rounded-lg shadow-lg p-8 max-w-lg w-full">
        <h2 class="text-xl font-bold mb-4">メンバーを招待する</h2>
        <p>招待する人に以下のURLを共有してください</p>
        <p class="mb-4">※LINEのアカウントが必要です。</p>
        <input type="email" id="inviteEmail" class="border rounded-lg w-full p-2 mb-4" readonly value="<%= add_mypage_group_group_member_url(group_id: @group.id, id: Encryption.encrypt(@group.id)) %>">
        <div class="flex justify-end gap-4">
            <button id="closeModal" class="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600">閉じる</button>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const inviteButton = document.getElementById('js-ionvite');
    const modal = document.getElementById('inviteModal');
    const closeModalButton = document.getElementById('closeModal');
    const inviteEmailInput = document.getElementById('inviteEmail');

    // モーダルを表示する関数
    function openModal() {
        modal.classList.remove('hidden');
        inviteEmailInput.focus();
    }

    // モーダルを非表示にする関数
    function closeModal() {
        modal.classList.add('hidden');
    }

    // テキストをクリップボードにコピーする関数
    function copyToClipboard() {
        inviteEmailInput.select();
        document.execCommand('copy');
        alert('コピーしました');
    }

    inviteButton.addEventListener('click', openModal);
    closeModalButton.addEventListener('click', closeModal);
    inviteEmailInput.addEventListener('click', copyToClipboard);

    // エスケープキーでモーダルを閉じる
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
            closeModal();
        }
    });
});
</script>